spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mapgenda_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8080
  servlet:
    context-path: /aventura

logging:
 level:
  root: INFO
com.aventura: DEBUG


# ☁️ Cloudinary
CLOUDINARY_CLOUD_NAME: tu_Id_Cloudinary
CLOUDINARY_API_KEY: tu_Apikey_Cloudinary
CLOUDINARY_API_SECRET: tu_Secret_Apikey_Cloudinary


